#!/usr/bin/env bash
# creating the 404-error_page

# Updating Packages before installation
sudo apt-get update
sudo apt-get install -y nginx

# the index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html

# carrying out a "moved permanently redirection" (301)
new_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/beckylicious;"
sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default

# making of the 404 not found error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
new_string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$new_string/" /etc/nginx/sites-enabled/default

# Testing configurations for syntax errors - nbest practices
sudo nginx -t

# reload nginx
sudo service nginx restart
